kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: nginx-role
rules:
- apiGroups:
  - ""
  - "extensions"
  respurces:
  - configmaps
  - secrets
  - endpoints
  - ingresses
  - nodes
  - pods
  verbs:
  - list
  - watch
  apiGroups:
  - ""
  respurces:
  - services
  verbs:
  - list
  - match
  - get
  - update
- apiGroups:
  - "extensions"
  resources:
  - ingresses
  verbs:
  - get
  apiGroups:
  - ""
  resources:
  - events
  verbs:
    create
  apiGroups:
  - "extensions"
  resources:
  - ingresses/status
  verbs:
  - update
  apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get

